-- MERCHANT DATA
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('ANZ001', 'BINGO REPUBLIC' ,'GBP');
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('DMD001', 'DRAMA STUDIOS' ,'GBP');
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('MRG001', 'TOURS AND OPERATOR' ,'GBP');
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('PHT001', 'THE COFFEE SHOP' ,'GBP');
--OFFER TYPE DATA
INSERT INTO TOFFTYPE(ID, OFFER_TYPE) VALUES (100057, '% off');
INSERT INTO TOFFTYPE(ID, OFFER_TYPE) VALUES (100058, '2 for 1');
INSERT INTO TOFFTYPE(ID, OFFER_TYPE) VALUES (100059, 'FREE');
INSERT INTO TOFFTYPE(ID, OFFER_TYPE) VALUES (100060, 'BUY AND SAVE');
--OFFER TYPE DATA
INSERT INTO TOFFER(TITLE, DESCRIPTION, MERCHANT_ID, TYPE_ID, VALID_FROM, VALID_TO) VALUES ('Save 10% on Purchase', 'For your next ride to or from My Car get you there. Just book online and enter discount code JIMM to receive 10% off your total fare.', 3, 100057, '2017-01-11', '2017-02-11');