-- MERCHANT DATA
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('ANZ001', 'IMPORT H2 BOOKS' ,'GBP');
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('DMD001', 'DIAMOND BOOKS' ,'GBP');
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('MRG001', 'MIRAGE BOOKS' ,'GBP');
INSERT INTO TMERCHNT(CODE, NAME, CURRENCY_CODE) VALUES ('PHT001', 'PHATE BOOKS' ,'GBP');
--OFFER TYPE DATA
INSERT INTO TOFFTYPE(ID, OFFER_TYPE) VALUES (100057, '% off');
-- PRODUCT DATA
--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020345, 'The Girl on the Train: A Novel', 8.99, 10, 1, 'A');
--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020346, 'Obsession in Death', 10.49, 1, 1, 'A');
--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020347, 'Big Little Lies', 3.99, 20, 1, 'P');

--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020345, 'The Girl on the Train: A Novel', 8.99, 5, 2, 'A');
--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020348, 'Private Vegas', 9.99, 2, 2, 'A');
--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020349, 'The Nightingale', 14, 1, 2, 'A');

--INSERT INTO TPRODUCT(PROD_CODE, PROD_NAME, SALE_PRICE, UNITS_IN_STOCK, ID , STATUS) VALUES (80020350, 'A Spool of Blue Thread: A Novel', 10, 3, 3, 'A');

--OFFER DATA
--INSERT INTO TOFFER(OFFER_ID,  OFFER_TYPE , DESCRIPTION , PROD_ID , PERCENT_OFF , DATE_FROM , DATE_TO ) VALUE (1, 'FIXED', 'Fixed Discount offer', 1, 2.00, null, null);
