--Merchant's Table
DROP TABLE TMERCHNT IF EXISTS;
CREATE TABLE TMERCHNT (ID SERIAL, CODE VARCHAR(8) UNIQUE, NAME VARCHAR(255), CURRENCY_CODE VARCHAR(3));
--Product's Table
--DROP TABLE TPRODUCT IF EXISTS;
--CREATE TABLE TPRODUCT (PROD_ID SERIAL, PROD_CODE VARCHAR(8), PROD_NAME VARCHAR(255), SALE_PRICE DECIMAL, UNITS_IN_STOCK SMALLINT, MERC_ID SMALLINT, STATUS CHAR(1));
--Offer's Table
DROP TABLE TOFFER IF EXISTS;
CREATE TABLE TOFFER (ID SERIAL, TITLE VARCHAR(20), DESCRIPTION VARCHAR(255), TYPE_ID BIGINT NOT NULL, CATEGORY_ID BIGINT NOT NULL, MERCHANT_ID BIGINT NOT NULL, VALID_FROM DATE, VALID_TO DATE);
--Offer's Table
DROP TABLE TOFFTYPE IF EXISTS;
CREATE TABLE TOFFTYPE (ID SERIAL, OFFER_TYPE VARCHAR(20));
--Offer Category
DROP TABLE TOFFCAT IF EXISTS;
CREATE TABLE TOFFCAT (ID SERIAL, CATEGORY_NAME VARCHAR(30), DESCRIPTION VARCHAR(200));


ALTER TABLE TOFFER
ADD FOREIGN KEY (TYPE_ID) REFERENCES TOFFTYPE(ID);
ALTER TABLE TOFFER
ADD FOREIGN KEY (CATEGORY_ID) REFERENCES TOFFCAT(ID);
ALTER TABLE TOFFER
ADD FOREIGN KEY (MERCHANT_ID) REFERENCES TMERCHNT(ID);